package com.chartering.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * One of the ways a {@link Port} gets written down.
 *
 * <p>The same idea as {@link TradeAreaAlias}, one level finer, and it exists for the same
 * reason that one does: nothing in this trade writes a name the same way twice. A single
 * week of this mailbox carried "ILLICHIVSK", "ILYICHEVSK" and "CHORNOMORSK" for one berth —
 * the port was renamed in 2016 and half the market never noticed — and
 * {@code findByExactName} finds none of the first two.
 *
 * <p>{@link #aliasKey} is generated by the database (the alias uppercased with every
 * non-alphanumeric character removed) and is what lookups compare, read-only here for the
 * reason it is generated there: a unique index on a key the application computes is a
 * guarantee only for as long as every writer remembers to compute it the same way.
 *
 * <p>An alias never wins over a port's own name. That is a rule in
 * {@code PortDirectory} rather than a constraint here, because the two tables cannot have
 * one index between them — but it is what makes an alias safe to add: the worst a wrong one
 * can do is answer a question no port name already answered.
 */
@Getter
@Setter
@Entity
@Table(name = "port_aliases")
public class PortAlias {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "port_id", nullable = false)
    private Port port;

    /** As a human would type it, punctuation and all. */
    @Column(nullable = false, length = 120)
    private String alias;

    @Column(name = "alias_key", length = 120, insertable = false, updatable = false)
    private String aliasKey;

    /**
     * The same normalisation the generated column applies, for callers resolving free text.
     * Kept beside the column it has to agree with — and identical to
     * {@link TradeAreaAlias#key(String)}, which is deliberate: one notion of "the same
     * spelling" across both vocabularies.
     */
    public static String key(String text) {
        return TradeAreaAlias.key(text);
    }
}
