package com.chartering.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * One of the ways a {@link TradeArea} gets written down.
 *
 * <p>This table is the reason the vocabulary is usable at all. A single week of this
 * mailbox carried "W.MED", "WEST MED", "SPAIN MED" and "W.ITALY" for the same water, and
 * "SPOT AT MARMARA", "OPEN AT ADRIATIC" and "= MOROCCO 7/9" as positions. Matching on the
 * area name would find none of them.
 *
 * <p>{@link #aliasKey} is generated by the database — the alias uppercased with every
 * non-alphanumeric character removed — and is what lookups compare. It is read-only here
 * for the same reason it is generated there: a unique index on a key the application
 * computes is a guarantee only for as long as every writer remembers to compute it the
 * same way.
 */
@Getter
@Setter
@Entity
@Table(name = "trade_area_aliases")
public class TradeAreaAlias {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "trade_area_id", nullable = false)
    private TradeArea tradeArea;

    /** As a human would type it, punctuation and all. */
    @Column(nullable = false, length = 100)
    private String alias;

    @Column(name = "alias_key", length = 100, insertable = false, updatable = false)
    private String aliasKey;

    /**
     * The same normalisation the generated column applies, for callers resolving free text
     * against the alias table. Kept here beside the column it has to agree with.
     */
    public static String key(String text) {
        if (text == null) return null;
        String stripped = text.replaceAll("[^A-Za-z0-9]", "").toUpperCase();
        return stripped.isEmpty() ? null : stripped;
    }
}
