-- What a vessel used to be called.
--
-- Ships are renamed by their owners constantly - on a sale, on a change of manager, on a
-- reflagging - and a position list that arrives on Monday may use a name this database has
-- never seen for a hull it has held for ten years. The IMO number is the only thing that
-- never moves, and it is exactly what a broker's circular leaves out.
--
-- The information is already here, spelled into the name column by whoever typed it:
--
--     LOIRE RIVER/ EX AMIKO
--     A LINE (EX ADALINE)
--     RIZIK BEY EX. VANGUARD
--     ELEMENTS / EX GUBERNATOR KAMCHATKI/ EX KATERINA
--
-- 299 of the 4,566 rows are written like that. As a name it is unusable - it goes out on
-- circulars, it sorts under the wrong letter, and searching for "AMIKO" finds it only by
-- accident of substring matching. As data it is a rename history, which is worth having.
--
-- So: one row per former name, and the name column left holding only the current name.


CREATE TABLE public.vessel_ex_names (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vessel_id bigint NOT NULL,
    CONSTRAINT vessel_ex_names_vessel_id_fkey FOREIGN KEY (vessel_id)
        REFERENCES public.vessels(id) ON DELETE CASCADE,

    name character varying(255) NOT NULL,

    -- Where this came from, so a name extracted by the migration below can be told apart
    -- from one somebody typed. 'backfill' rows are a machine's reading of a free-text
    -- field and are the ones to suspect first if a vessel ever looks wrong.
    source character varying(20) DEFAULT 'manual' NOT NULL,

    -- When she was renamed, if anyone knows. Almost never filled from a backfill - the old
    -- name was recorded, the date it stopped being current was not - which is why it is
    -- nullable and why nothing orders by it.
    renamed_at date,

    notes text,

    created_at timestamp with time zone DEFAULT now()
);

-- One vessel does not carry the same former name twice, however many lists said so.
CREATE UNIQUE INDEX ux_vessel_ex_names_vessel_name
    ON public.vessel_ex_names USING btree (vessel_id, upper(name));

CREATE INDEX ix_vessel_ex_names_vessel ON public.vessel_ex_names USING btree (vessel_id);

-- The same trigram index the vessels table carries on its own name, and for the same
-- reason: the search box has to find a vessel by a fragment of a former name as readily as
-- by a fragment of the current one, or extracting these has made the data harder to reach
-- rather than easier.
CREATE INDEX ix_vessel_ex_names_name_trgm
    ON public.vessel_ex_names USING gin (lower((name)::text) public.gin_trgm_ops);


-- ---------------------------------------------------------------------------
-- The backfill
-- ---------------------------------------------------------------------------
-- THE PATTERN, and why it is this one.
--
--     (^|[\s/(),-])ex[\s.-]+
--
-- "ex" only where a separator precedes it, so ALEX S, EXPRESS and NEXUS are not touched -
-- and only where a separator follows it, which is the other half of the same guard. Every
-- one of the 299 rows uses a delimiter of some kind before the ex and a space, dot or dash
-- after it; the three chained ones (ELEMENTS above) repeat the whole construction, which
-- is why this splits rather than matching once.
--
-- Trimming takes whitespace and the bracketing punctuation off both ends but LEAVES
-- hyphens alone. Names like -AGNESKA- and -ILIS- wear those dashes as a marker of their
-- own in this database, and stripping them here would quietly rename a hundred vessels
-- that this migration has no business touching.
--
-- The working table is dropped explicitly at the foot of this file rather than with
-- ON COMMIT DROP. Flyway runs a migration inside one transaction and either would do here,
-- but a migration that only works when something else has opened a transaction for it
-- cannot be tried out by hand against the local database - which is the one place a data
-- migration of 299 rows should be tried out.
CREATE TEMPORARY TABLE tmp_ex_split AS
SELECT v.id AS vessel_id,
       btrim(s.part, E' \t/(),.') AS part,
       s.ord
FROM public.vessels v
CROSS JOIN LATERAL regexp_split_to_table(v.name, '(^|[\s/(),-])ex[\s.-]+', 'i')
     WITH ORDINALITY AS s(part, ord)
WHERE v.name ~* '(^|[\s/(),-])ex[\s.-]+';

-- Every part after the first is a former name.
INSERT INTO public.vessel_ex_names (vessel_id, name, source)
SELECT vessel_id, part, 'backfill'
FROM tmp_ex_split
WHERE ord > 1
  AND part <> ''
ON CONFLICT DO NOTHING;

-- The first part is what she is called now.
--
-- Guarded on the result being non-empty: a row spelled "EX SOMETHING", with nothing before
-- the ex, would otherwise be left with a blank name - a NOT NULL column satisfied by a
-- value that means nothing, which is the worst of both. Such a row keeps its original name
-- and shows up as a vessel whose name still contains "EX", which is a visible problem
-- rather than a silent one.
UPDATE public.vessels v
SET name = s.part
FROM tmp_ex_split s
WHERE s.vessel_id = v.id
  AND s.ord = 1
  AND s.part <> ''
  AND s.part <> v.name;

DROP TABLE tmp_ex_split;
