-- Cargoes in hand.
--
-- What arrives, in full, from this mailbox:
--
--     25,000 MT Wheat +/- 10%
--     Chornomorsk, Ukraine -> Spain Mediterranean
--     Suitable geared bulk carrier, approx. 28,000-35,000 DWT
--     Laycan: Please advise suitable open tonnage
--
-- and, at the other end of the scale, "approximately 5,000 MT of HBI from Misurata, Libya
-- to Alexandria, Egypt", with no laycan, no terms and no freight idea at all.
--
-- The columns below are that enquiry taken apart. Nearly all of them are nullable, because
-- nearly all of them are absent from a real first email - and a cargo that cannot be
-- written down until it is complete is a cargo that gets written on paper instead.
--
-- The field names deliberately track the cargo half of the annotation template the mail
-- corpus is being labelled against (commodity, quantity, quantityTolerance, loadPort,
-- loadRange, dischargePort, dischargeRange, laycanFrom, laycanTo, terms, freightIdea,
-- commission). When the parser lands, its output should drop into these columns without a
-- translation layer in between, and a translation layer is exactly what a second set of
-- names for the same facts would become.

CREATE TABLE public.cargoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Where it has got to. OPEN, QUOTED, FIRM, FIXED, FAILED, EXPIRED, WITHDRAWN, held as
    -- text rather than an enum type for the reason the rest of this schema does: adding a
    -- state to a Postgres enum is a migration, adding one to a varchar is a line in Java,
    -- and this list will move while the desk works out what it actually tracks.
    status character varying(20) DEFAULT 'OPEN' NOT NULL,
    status_note text,

    commodity character varying(120) NOT NULL,

    -- Cubic feet per tonne. The number that decides whether a cargo cubes out before it
    -- weighs out - 5,000 tonnes of HBI and 5,000 tonnes of grain want very different holds
    -- - and the only way Match can compare a quantity against a grain capacity rather than
    -- just against deadweight.
    stowage_factor numeric(6,2),

    -- FOUR COLUMNS FOR ONE NUMBER, and each earns its place.
    --
    -- quantity + quantity_tolerance are what the email said and what the form shows:
    -- "25,000 MT" and "+/- 10%". The tolerance is text because it is not always a
    -- percentage - MOLOO, MOLCO, "10 pct in owner's option" and "min 4,800" all turn up.
    --
    -- quantity_min / quantity_max are what Match compares a hull against. Derived from the
    -- other two when the tolerance is a plain percentage, typed by hand when it is not.
    -- Storing the range rather than recomputing it is what lets a size search stay one
    -- indexed comparison, and what lets a broker override a range the arithmetic got wrong.
    quantity numeric,
    quantity_unit character varying(10) DEFAULT 'MT' NOT NULL,
    quantity_tolerance character varying(30),
    quantity_min numeric,
    quantity_max numeric,

    -- Load and discharge, each said three ways because an email says whichever it knows.
    --
    -- The port id is the precise answer; the area is the coarse one ("Spain Med" names no
    -- port at all); the text keeps what was actually written, so a port not on file is not
    -- lost while somebody decides whether to add it. Match reads the port's own area when
    -- there is a port, and falls back to the area column when there is not.
    load_port_id bigint,
    load_port_text character varying(160),
    load_area_id bigint,

    discharge_port_id bigint,
    discharge_port_text character varying(160),
    discharge_area_id bigint,

    -- The laycan. Dates for matching, text for what the email said - including "please
    -- advise suitable open tonnage", which is a real laycan in the sense that it is what
    -- the charterer told us, and no date at all in the sense Match needs.
    laycan_from date,
    laycan_to date,
    laycan_text character varying(80),

    -- Restrictions the cargo imposes on the ship. Nullable throughout: null is "the
    -- charterer has not said", which is not the same as "no limit", and Match says which
    -- of the two it is looking at rather than assuming.
    max_draft numeric,
    min_dwt numeric,
    max_dwt numeric,
    max_age_years smallint,
    requires_geared boolean,
    requires_grain_fitted boolean,
    requires_imo_fitted boolean,

    -- Commercials, all free text. Freight is quoted as "USD 25 pmt", "abt 24.50 fio",
    -- "lumpsum 120k" and "market related" in the same week; a numeric column would take
    -- the first of those and lose the rest.
    freight_idea character varying(120),
    commission character varying(60),
    terms character varying(200),
    load_rate character varying(60),
    discharge_rate character varying(60),

    -- Who it came from. The charterer is often not known at first - the enquiry arrives
    -- through a broker who is not saying yet - which is why these are three separate
    -- nullable links rather than one "counterparty".
    charterer_company_id bigint,
    broker_company_id bigint,
    broker_person_id bigint,

    -- Provenance. from_mail records that this cargo was read out of an email rather than
    -- typed, and stays true even after the message it came from is gone: the fact is about
    -- the cargo, and mail_messages is a mirror of a server whose folders get cleaned out.
    -- Same reasoning, and the same ON DELETE SET NULL, as analysis samples and replies.
    from_mail boolean DEFAULT false NOT NULL,
    source_mail_message_id bigint,
    received_at timestamp with time zone,

    notes text,

    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),

    CONSTRAINT cargoes_load_port_fkey FOREIGN KEY (load_port_id)
        REFERENCES public.ports(id) ON DELETE SET NULL,
    CONSTRAINT cargoes_discharge_port_fkey FOREIGN KEY (discharge_port_id)
        REFERENCES public.ports(id) ON DELETE SET NULL,
    CONSTRAINT cargoes_load_area_fkey FOREIGN KEY (load_area_id)
        REFERENCES public.trade_areas(id) ON DELETE SET NULL,
    CONSTRAINT cargoes_discharge_area_fkey FOREIGN KEY (discharge_area_id)
        REFERENCES public.trade_areas(id) ON DELETE SET NULL,
    CONSTRAINT cargoes_charterer_fkey FOREIGN KEY (charterer_company_id)
        REFERENCES public.companies(id) ON DELETE SET NULL,
    CONSTRAINT cargoes_broker_company_fkey FOREIGN KEY (broker_company_id)
        REFERENCES public.companies(id) ON DELETE SET NULL,
    CONSTRAINT cargoes_broker_person_fkey FOREIGN KEY (broker_person_id)
        REFERENCES public.people(id) ON DELETE SET NULL,
    CONSTRAINT cargoes_source_mail_fkey FOREIGN KEY (source_mail_message_id)
        REFERENCES public.mail_messages(id) ON DELETE SET NULL
);

-- The Cargoes tab opens on live work, newest first, and Match reads the same set.
CREATE INDEX ix_cargoes_status ON public.cargoes USING btree (status);
CREATE INDEX ix_cargoes_laycan ON public.cargoes USING btree (laycan_from, laycan_to);
CREATE INDEX ix_cargoes_load_area ON public.cargoes USING btree (load_area_id);
CREATE INDEX ix_cargoes_load_port ON public.cargoes USING btree (load_port_id);
CREATE INDEX ix_cargoes_received ON public.cargoes USING btree (received_at DESC);

-- Same trigram treatment the vessel and company names get: "whea" has to find Wheat, and
-- a commodity is typed differently by everyone who types it.
CREATE INDEX ix_cargoes_commodity_trgm
    ON public.cargoes USING gin (lower((commodity)::text) public.gin_trgm_ops);
