-- Where a ship is free, and when.
--
-- One row per position we are told about, not one per vessel. This is the whole design
-- decision, and it is the one that everything else on the Open Fleet tab follows from:
--
--   * A position is a fact with a date on it. "SPOT AT MARMARA" was true on Monday and is
--     a lie by Friday. Overwriting a column would leave no way to know which.
--   * The same hull is reported by several people. GN's list and Interscan's list both
--     carry vessels this desk knows, and they disagree - about the dates, sometimes about
--     the deadweight. Two rows is the honest record; one row is whichever email synced
--     last.
--   * The history is worth more than the current state. A vessel that has opened in the
--     Adriatic five times this year is a vessel to remember when an Adriatic cargo lands,
--     and that pattern only exists if the old rows were kept.
--   * The parser that lands later inserts rows. It does not have to reason about what it
--     is replacing, which is the kind of reasoning a parser gets wrong quietly.
--
-- The Open Fleet tab therefore shows the newest live row per vessel, and the vessel's
-- record shows the list.

CREATE TABLE public.vessel_positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vessel_id bigint NOT NULL,
    CONSTRAINT vessel_positions_vessel_fkey FOREIGN KEY (vessel_id)
        REFERENCES public.vessels(id) ON DELETE CASCADE,

    -- LIVE, FIXED, WITHDRAWN, SUPERSEDED, EXPIRED. SUPERSEDED is what a newer report from
    -- the same source does to an older one, and it is a status rather than a delete
    -- because "she was said to be open Adriatic and then wasn't" is the sort of thing a
    -- broker wants to be able to look back at.
    status character varying(20) DEFAULT 'LIVE' NOT NULL,

    -- Where she opens, said three ways, for the same reason a cargo's load point is:
    -- "SALERNO 1/2 SEPT" names a port, "SPOT AT MARMARA" names only an area, and
    -- "= MOROCCO 7/9" names a country. Match reads the port's area when there is a port
    -- and the area column when there is not.
    open_port_id bigint,
    open_port_text character varying(160),
    open_area_id bigint,

    -- The dates. "01 / 02 SEPT" is a range; "SPOT" is a range that started already and is
    -- recorded as an open_from of today with no open_to, with the word itself kept in
    -- open_text so the screen can show what was said.
    open_from date,
    open_to date,
    open_text character varying(80),

    -- What she just carried. Asked about constantly and almost never recorded: a hold that
    -- last had cement in it is not offered for grain without a cleaning conversation.
    last_cargo character varying(160),

    -- What her owners want next. Free text on purpose - "prefers grain, no scrap, no
    -- Israel, min 20 days duration" is one sentence in an email and would be five badly
    -- fitting columns here. Match reads the vessel's own fitted flags for the hard
    -- constraints and shows this to the broker for the rest.
    cargo_preferences text,

    -- Who said so. A position is only as good as its source, and a list from the owner is
    -- worth more than the same line forwarded by a third broker.
    reported_by_company_id bigint,
    reported_by_person_id bigint,

    -- Provenance, matching cargoes exactly: the fact that it came out of an email outlives
    -- the email, so the boolean is separate from the nullable link.
    from_mail boolean DEFAULT false NOT NULL,
    source_mail_message_id bigint,

    -- When we were told, which is not when the row was written: a list read out of a
    -- three-day-old email is three days old, and staleness is the first thing to show on
    -- the Open Fleet tab.
    reported_at timestamp with time zone DEFAULT now() NOT NULL,

    notes text,

    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),

    CONSTRAINT vessel_positions_open_port_fkey FOREIGN KEY (open_port_id)
        REFERENCES public.ports(id) ON DELETE SET NULL,
    CONSTRAINT vessel_positions_open_area_fkey FOREIGN KEY (open_area_id)
        REFERENCES public.trade_areas(id) ON DELETE SET NULL,
    CONSTRAINT vessel_positions_reported_company_fkey FOREIGN KEY (reported_by_company_id)
        REFERENCES public.companies(id) ON DELETE SET NULL,
    CONSTRAINT vessel_positions_reported_person_fkey FOREIGN KEY (reported_by_person_id)
        REFERENCES public.people(id) ON DELETE SET NULL,
    CONSTRAINT vessel_positions_source_mail_fkey FOREIGN KEY (source_mail_message_id)
        REFERENCES public.mail_messages(id) ON DELETE SET NULL
);

-- "The newest position for this vessel", which is the question the Open Fleet tab and
-- Match both ask, once per vessel.
CREATE INDEX ix_vessel_positions_vessel_reported
    ON public.vessel_positions USING btree (vessel_id, reported_at DESC);

CREATE INDEX ix_vessel_positions_status ON public.vessel_positions USING btree (status);
CREATE INDEX ix_vessel_positions_open_area ON public.vessel_positions USING btree (open_area_id);
CREATE INDEX ix_vessel_positions_open_from ON public.vessel_positions USING btree (open_from);


-- ---------------------------------------------------------------------------
-- What was done about a pairing
-- ---------------------------------------------------------------------------
-- Match itself computes; it stores nothing about which vessels suit which cargo, because a
-- stored score is a score that goes stale the moment a position or a cargo moves, and a
-- table of them would need invalidating on every write in the feature.
--
-- What does need storing is the human's answer. Without it the tab proposes the same
-- fifteen ships against the same cargo every morning, including the four already offered
-- and the two the owner declined on Tuesday - which is how a screen that was supposed to
-- save work becomes work.
--
-- One row per cargo and vessel, holding the last thing that happened between them.
CREATE TABLE public.cargo_vessel_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cargo_id bigint NOT NULL,
    vessel_id bigint NOT NULL,

    -- SHORTLISTED, OFFERED, DECLINED, FIXED, DISMISSED. DISMISSED is the important one:
    -- it means "not this ship for this cargo, stop showing me", and it is why the table
    -- exists.
    outcome character varying(20) NOT NULL,
    note text,

    -- The position this was decided against, so a decision can be read back against what
    -- was known at the time rather than against wherever she is now. Nullable and
    -- SET NULL: the decision survives the position being superseded, which it will be.
    vessel_position_id bigint,

    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    decided_by character varying(255),

    CONSTRAINT cargo_vessel_matches_cargo_fkey FOREIGN KEY (cargo_id)
        REFERENCES public.cargoes(id) ON DELETE CASCADE,
    CONSTRAINT cargo_vessel_matches_vessel_fkey FOREIGN KEY (vessel_id)
        REFERENCES public.vessels(id) ON DELETE CASCADE,
    CONSTRAINT cargo_vessel_matches_position_fkey FOREIGN KEY (vessel_position_id)
        REFERENCES public.vessel_positions(id) ON DELETE SET NULL
);

-- One standing answer per pairing - offering a ship twice is a correction to the first
-- answer, not a second one.
CREATE UNIQUE INDEX ux_cargo_vessel_matches_pair
    ON public.cargo_vessel_matches USING btree (cargo_id, vessel_id);

CREATE INDEX ix_cargo_vessel_matches_vessel ON public.cargo_vessel_matches USING btree (vessel_id);
