-- Reading the mail: what the parser did, and what it could not decide on its own.
--
-- The model that reads a cargo offer or a position list runs outside this application (see
-- the sibling chartering-ml project: llama.cpp serving a finetuned Qwen3-4B behind a JSON
-- schema). Nothing here calls a model at write time and nothing here stores weights. These
-- three tables hold the three things that survive a parse: what was read, what a human still
-- has to answer, and who told us about a cargo.
--
-- The division of labour is the point, and it is the answer to "what may a machine write
-- unattended". A position for a hull already on file and a cargo nothing else looks like are
-- written straight through, because both are append-only records of what an email said and
-- neither destroys anything if the reading was wrong - a bad position is superseded by the
-- next list, a bad cargo is deleted from the Cargoes tab. Everything that would *change* a
-- record already on file - a deadweight that disagrees, a hull nobody has heard of, a cargo
-- that looks like one already in hand - stops and waits, because those are the readings that
-- overwrite something a person put there.


-- ---------------------------------------------------------------------------
-- One row per message the parser has read
-- ---------------------------------------------------------------------------
-- Also the dedupe: a message with a row here is never read again, which is what makes "sweep
-- the mailbox" safe to run on a timer and safe to run twice. A failed parse gets a row too -
-- the model was down, the answer did not parse - and is retried while attempts is under the
-- configured ceiling, because "the GPU box was asleep" and "this email defeats the model"
-- are both real and only the second one is permanent.
CREATE TABLE public.parsed_emails (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mail_message_id bigint NOT NULL,
    CONSTRAINT parsed_emails_message_fkey FOREIGN KEY (mail_message_id)
        REFERENCES public.mail_messages(id) ON DELETE CASCADE,

    -- PARSED, FAILED, SKIPPED. SKIPPED is an email with no body worth sending - an
    -- attachment-only position list, a calendar invite - recorded rather than left out so
    -- the sweep does not pick it up again every hour for the rest of its life.
    status character varying(20) NOT NULL,

    -- The model's own classification: cargo_offer, vessel_opening, mixed, other. Kept as
    -- the model said it rather than mapped onto an enum here: it is evidence about the
    -- parse, and 'other' is the value that explains an email that produced nothing.
    email_type character varying(30),

    -- The answer, verbatim. The applied half is already in cargoes and vessel_positions;
    -- this is what those were derived from, and it is the only thing that can settle "did
    -- the model read it wrong or did we file it wrong". Not indexed and not queried - it is
    -- read one row at a time, from a drawer.
    raw_json text,

    -- Which server answered, so a corpus retrained next month is distinguishable from the
    -- one that produced last month's rows. Free text: it is whatever the endpoint reported.
    model_name character varying(160),

    -- What it cost, for the Intake tab's own honesty about how long a sweep takes.
    prompt_chars integer,
    duration_ms integer,

    -- What the parse produced, denormalised on purpose. The alternative is three COUNT(*)
    -- subqueries per row on a list that is read far more often than it is written, and two
    -- of the three cannot be counted at all after the fact: a cargo merged into an existing
    -- one leaves no row pointing back here, and a position skipped as an exact re-report
    -- leaves nothing whatsoever.
    positions_applied integer DEFAULT 0 NOT NULL,
    cargoes_applied integer DEFAULT 0 NOT NULL,
    items_raised integer DEFAULT 0 NOT NULL,

    -- Why it failed, in the words the user has to act on ("Connect timed out" means the
    -- model server is not running).
    error text,
    attempts integer DEFAULT 1 NOT NULL,

    parsed_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- One reading per message. The sweep's "what have I not read yet" is a NOT EXISTS against
-- this, so the constraint is both the dedupe and the index that answers it.
CREATE UNIQUE INDEX ux_parsed_emails_message ON public.parsed_emails USING btree (mail_message_id);
CREATE INDEX ix_parsed_emails_status ON public.parsed_emails USING btree (status);
CREATE INDEX ix_parsed_emails_parsed_at ON public.parsed_emails USING btree (parsed_at DESC);


-- ---------------------------------------------------------------------------
-- What the parser would not decide on its own
-- ---------------------------------------------------------------------------
-- The review queue behind the Intake tab. Three kinds, and each is a different question:
--
--   NEW_VESSEL     - a position naming a hull this database has never held. Accepting it
--                    creates the vessel and her position; the alternative is pointing it at
--                    a ship already on file, which is the same answer a renamed vessel needs.
--   VESSEL_FIELDS  - she is on file and the email disagrees about her. One row lists every
--                    field that differs, and the user accepts all of them or the ones they
--                    believe. This is the screen the whole feature was asked for.
--   CARGO_MERGE    - a cargo that looks like one already in hand, usually because two
--                    brokers are working the same charterer. Merge and keep both senders, or
--                    keep it as a separate cargo.
--
-- The payload is JSON held as text, and deliberately so: it is a proposal, not a record. Its
-- shape follows the parser's output, which is still moving, and a set of columns per kind
-- would be a migration every time the extraction template grows a field - to store rows
-- whose whole lifetime is measured in days. Nothing queries inside it.
CREATE TABLE public.intake_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    parsed_email_id bigint NOT NULL,
    CONSTRAINT intake_items_parsed_email_fkey FOREIGN KEY (parsed_email_id)
        REFERENCES public.parsed_emails(id) ON DELETE CASCADE,

    kind character varying(20) NOT NULL,
    -- PENDING, ACCEPTED, REJECTED. Resolved rows are kept: "I said no to this ship on
    -- Tuesday" is the same fact a dismissed match is, and a queue that deletes its answers
    -- proposes them again on the next list.
    status character varying(20) DEFAULT 'PENDING' NOT NULL,

    -- What it is about, as far as the parser got. Every one is nullable because which of
    -- them is set is what the kind means: a NEW_VESSEL has no vessel yet, a CARGO_MERGE has
    -- the cargo it wants to merge into.
    vessel_id bigint,
    cargo_id bigint,

    -- The name as the email spelled it, so the queue reads as a list of ships and cargoes
    -- rather than a list of ids. Also the only trace left of a NEW_VESSEL that was rejected.
    subject_label character varying(255),

    payload text NOT NULL,

    resolved_at timestamp with time zone,
    resolved_by character varying(255),
    resolution_note text,

    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),

    -- SET NULL rather than CASCADE on both: deleting a vessel must not silently delete the
    -- record of a decision made about her, and an item whose subject has gone is still
    -- readable through its payload and its label.
    CONSTRAINT intake_items_vessel_fkey FOREIGN KEY (vessel_id)
        REFERENCES public.vessels(id) ON DELETE SET NULL,
    CONSTRAINT intake_items_cargo_fkey FOREIGN KEY (cargo_id)
        REFERENCES public.cargoes(id) ON DELETE SET NULL
);

-- The tab's default view is "everything still pending, oldest first", which is this index.
CREATE INDEX ix_intake_items_status_created ON public.intake_items USING btree (status, created_at);
CREATE INDEX ix_intake_items_kind ON public.intake_items USING btree (kind);
CREATE INDEX ix_intake_items_parsed_email ON public.intake_items USING btree (parsed_email_id);


-- ---------------------------------------------------------------------------
-- Who told us about a cargo
-- ---------------------------------------------------------------------------
-- A cargo already carries one broker, one charterer and one source message, which is right
-- for a cargo somebody typed. It is wrong the moment the same requirement arrives from two
-- brokers, which is normal: a charterer works several, and this desk hears the same enquiry
-- three times in a morning with the quantity phrased differently each time.
--
-- Merging them into one cargo is what the Cargoes tab and Match need - the same cargo listed
-- three times is three chances to offer the same ship - but the merge must not throw away
-- who said what. Every reporting email keeps a row here, so "who else is working this" is
-- answerable and so is "which email did that laycan come out of".
--
-- Not a replacement for cargoes.broker_company_id: that column is who this cargo is worked
-- through, an editable fact about the cargo. This table is a log of arrivals.
--
-- Positions need no equivalent. vessel_positions is already one row per report carrying its
-- own reported_by_company_id, and Open Fleet collapses them to the newest per hull - so the
-- combined view and every reporter behind it are both already there.
CREATE TABLE public.cargo_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cargo_id bigint NOT NULL,
    CONSTRAINT cargo_sources_cargo_fkey FOREIGN KEY (cargo_id)
        REFERENCES public.cargoes(id) ON DELETE CASCADE,

    -- SET NULL, matching cargoes.source_mail_message_id: mail_messages mirrors a server
    -- whose folders get emptied, and the fact that a broker sent this cargo outlives the
    -- copy of their email.
    mail_message_id bigint,
    CONSTRAINT cargo_sources_message_fkey FOREIGN KEY (mail_message_id)
        REFERENCES public.mail_messages(id) ON DELETE SET NULL,

    reported_by_company_id bigint,
    reported_by_person_id bigint,

    -- The address it came from, kept as text as well as through the link. A sender with no
    -- contact row still has to be attributable, and this is the whole of what we know then.
    from_address character varying(320),

    -- When they told us. The newest row here is what "last heard about this cargo" means,
    -- which is the staleness the Cargoes tab reads.
    reported_at timestamp with time zone DEFAULT now() NOT NULL,

    notes text,
    created_at timestamp with time zone DEFAULT now(),

    CONSTRAINT cargo_sources_company_fkey FOREIGN KEY (reported_by_company_id)
        REFERENCES public.companies(id) ON DELETE SET NULL,
    CONSTRAINT cargo_sources_person_fkey FOREIGN KEY (reported_by_person_id)
        REFERENCES public.people(id) ON DELETE SET NULL
);

-- One row per cargo per email. Re-parsing a message cannot double up its sources, and a
-- broker who repeats himself in a second email is a second row, which is correct - that is
-- a second arrival.
CREATE UNIQUE INDEX ux_cargo_sources_cargo_message
    ON public.cargo_sources USING btree (cargo_id, mail_message_id)
    WHERE mail_message_id IS NOT NULL;

CREATE INDEX ix_cargo_sources_cargo ON public.cargo_sources USING btree (cargo_id, reported_at DESC);
CREATE INDEX ix_cargo_sources_company ON public.cargo_sources USING btree (reported_by_company_id);
