-- Looking a hull up on the open web, when the mail and this database between them cannot
-- say who she is.
--
-- The case this exists for: a position list names "LADY MERAL", gives a deadweight and a
-- build year, and no IMO. This database has no hull of that name. The desk's own answer is
-- to type the name into a ship database and read the number off, and that is exactly what
-- this automates - one search, the candidates it returns, and a person deciding which if any
-- is her.
--
-- WHAT THIS IS NOT. It is not a source of record and it must never be treated as one. Every
-- value it produces is a proposal that a person accepts field by field, and the row below
-- keeps the whole answer plus the page it came off, so a figure that later looks wrong can
-- be traced to the search that produced it. Provenance is the point of the table, not a
-- by-product: once a deadweight has been accepted it is indistinguishable from one a broker
-- typed unless something remembers where it came from.
--
-- One row per attempt, kept whether it found anything or not. A search that returned nothing
-- is an answer - it stops the same hull being looked up again every hour - and a search that
-- failed is a fact about the source rather than about the ship.
CREATE TABLE public.vessel_lookups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What prompted it. Lookups are run for hulls sitting in the review queue, so the item
    -- is the natural owner: answer the item and the lookup has done its job. CASCADE for the
    -- same reason - a proposal outliving the question it was raised against is litter.
    intake_item_id bigint,
    CONSTRAINT vessel_lookups_item_fkey FOREIGN KEY (intake_item_id)
        REFERENCES public.intake_items(id) ON DELETE CASCADE,

    -- Set once the lookup has been applied to a hull, so a vessel's record can be traced
    -- back to the search that supplied part of it. SET NULL: deleting a ship must not delete
    -- the evidence of where her particulars came from.
    vessel_id bigint,
    CONSTRAINT vessel_lookups_vessel_fkey FOREIGN KEY (vessel_id)
        REFERENCES public.vessels(id) ON DELETE SET NULL,

    -- Which source answered, as configured. Free text rather than an enum: the source is a
    -- deployment's choice and will change - a paid API replacing a scraped page is the
    -- expected direction of travel, and it should not need a migration.
    provider character varying(60) NOT NULL,

    -- What was searched for, in the words that were sent. The first thing to look at when a
    -- lookup returns somebody else's ship.
    query character varying(255) NOT NULL,

    -- OK, NO_MATCH, FAILED. NO_MATCH is a result and not an error: most of this fleet is
    -- small tonnage that a public ship database may simply not carry.
    status character varying(20) NOT NULL,

    -- Every candidate the search returned, as read, before any matching was applied. Kept
    -- whole rather than just the winner: when the wrong hull is proposed, the question is
    -- always what else was on offer, and a row holding only the answer cannot say.
    candidates_json text,

    -- The one the matcher preferred, and how sure it was. Nullable because a search can
    -- return candidates and none of them be a plausible match.
    matched_imo character varying(20),
    confidence integer,

    -- The page a person can open to check for themselves. The whole feature rests on being
    -- checkable: a number with no source is a rumour.
    source_url character varying(500),

    error text,

    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- "Has this item been looked up yet" - what the enrichment pass asks, once per item.
CREATE UNIQUE INDEX ux_vessel_lookups_item
    ON public.vessel_lookups USING btree (intake_item_id)
    WHERE intake_item_id IS NOT NULL;

CREATE INDEX ix_vessel_lookups_vessel ON public.vessel_lookups USING btree (vessel_id);
CREATE INDEX ix_vessel_lookups_fetched ON public.vessel_lookups USING btree (fetched_at DESC);
