-- Where a berth actually is, and how far it is from another one by sea.
--
-- WHAT THIS FIXES. Until now the only thing Match could say about distance was
-- trade_area_distances: a broker's round number of ballast days between two waters, seeded
-- for the sixty-odd pairs this desk would consider. That was the right first answer and it
-- is not the last one, because it cannot tell Constanza from Rostov. Both are "Black Sea";
-- one is a deepwater berth two hours off the shipping lane and the other is 250 miles up
-- the Don and behind the Kerch Strait. A cargo loading Constanza with a laycan four days
-- out is a cargo the Rostov ship cannot make, and the area table says she can.
--
-- Four things arrive here, and none of them replaces the area table:
--
--   port_aliases                       the spellings a broker writes a berth as, the same
--                                      idea and the same shape as trade_area_aliases
--   ports.latitude/longitude/country   where the berth is, and which country it is in
--   sea_waypoints                      open-water points, and the straits between them
--   sea_legs                           which two waypoints have open water between them
--
-- WHY A WAYPOINT GRAPH RATHER THAN A DISTANCE TABLE OR A STRAIGHT LINE.
--
-- A straight line is wrong in the direction that loses money. Odessa to Genoa on a great
-- circle crosses Bulgaria, Serbia and the Alps: 1,050 miles and four days, where the real
-- answer is 1,700 miles and six and a half. A screen that offers a ship for a laycan she
-- misses by two days is worse than one that offers nothing, because the offer gets made.
--
-- A full port-to-port matrix is the other extreme. 283 ports is forty thousand pairs, every
-- one of them a number somebody has to be right about and keep true when a port is added.
-- Nobody would.
--
-- So: a small network of points that are genuinely at sea, joined by legs whose water is
-- genuinely open, and each port hung off the nearest one. Sixty nodes and a hundred legs
-- describe every route this desk quotes, a new port costs one gateway link, and the answer
-- for a pair nobody thought about is computed rather than guessed. It also makes the
-- chokepoints explicit, which on a Black Sea desk is most of the point: everything out of
-- this range goes through the Bosphorus and the Dardanelles, and the wait for a convoy is a
-- real part of the passage rather than a rounding error.
--
-- A ROUTE THAT DOES NOT EXIST IS AN ANSWER. The Caspian gets a waypoint with no legs at all,
-- so no route is ever found out of it -- the same honest "too far to consider" the sparse
-- area table gives, arrived at by the same reasoning. And the application falls back to the
-- area table wherever the network answers nothing, so a port this file forgot to place is no
-- worse off than it is today.


-- ---------------------------------------------------------------------------
-- 1. The ways a port is written
-- ---------------------------------------------------------------------------
-- Deliberately the same shape as trade_area_aliases, down to the generated key and the
-- unique index on it, because it is deliberately the same idea. A position list writes
-- "ILLICHIVSK", "ILYICHEVSK" and "CHORNOMORSK" for one berth in one week -- the port was
-- renamed in 2016 and half the market never noticed -- and Port.findByExactName finds none
-- of them.
--
-- alias_key is computed by the database for the reason it is there: a unique index on a key
-- the application computes is a guarantee only for as long as every writer remembers to
-- compute it the same way.
CREATE TABLE public.port_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    port_id bigint NOT NULL,
    CONSTRAINT port_aliases_port_fkey FOREIGN KEY (port_id)
        REFERENCES public.ports(id) ON DELETE CASCADE,

    -- As a human would type it, punctuation and all.
    alias character varying(120) NOT NULL,

    alias_key character varying(120)
        GENERATED ALWAYS AS (upper(regexp_replace(alias, '[^A-Za-z0-9]', '', 'g'))) STORED
);

-- One spelling means one berth, or the vocabulary is ambiguous -- and an ambiguous
-- vocabulary is worse than none, because the resolver would silently take whichever row it
-- read first and file a ship in the wrong sea. Where a name genuinely is ambiguous
-- ("Tripoli", "Victoria") the answer is to leave it out and let the words stand, which is
-- what the ports table already does with "Tripoli (Lebanon)" and "Tripoli (Libya)".
CREATE UNIQUE INDEX ux_port_aliases_key ON public.port_aliases USING btree (alias_key);
CREATE INDEX ix_port_aliases_port ON public.port_aliases USING btree (port_id);


-- ---------------------------------------------------------------------------
-- 2. The network
-- ---------------------------------------------------------------------------
-- A waypoint is a point at sea, and it is one of two kinds. Most are open water in the
-- middle of something a ship crosses in a straight line -- the central Black Sea, the
-- Tyrrhenian, the Arabian Sea. The rest are the places where the water narrows and every
-- route through the region has to pass: the Bosphorus, the Dardanelles, Gibraltar, Suez, the
-- Kerch Strait, Bab el Mandeb, Hormuz, Malacca.
--
-- The second kind is why the graph is worth having at all. They are where the delays are,
-- and on this desk the Bosphorus queue is not a detail: a bulker can sit at anchor off Kavak
-- for the better part of a day waiting for a northbound convoy, and a laycan calculation
-- that leaves it out is a day optimistic on every Black Sea passage there is.
CREATE TABLE public.sea_waypoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code character varying(24) NOT NULL,
    name character varying(100) NOT NULL,

    latitude numeric(8,5) NOT NULL,
    longitude numeric(8,5) NOT NULL,

    -- Hours a ship loses here over and above the time to sail through: convoy waits,
    -- pilotage, canal transit. Charged once per passage through the point, and 0 on the
    -- open-water nodes, which is most of them.
    delay_hours numeric(5,1) DEFAULT 0 NOT NULL,

    notes text
);

CREATE UNIQUE INDEX ux_sea_waypoints_code ON public.sea_waypoints USING btree (code);


-- A leg asserts one thing: that the water between these two waypoints is open, so a ship
-- sails it in a straight line. That is what makes distance_nm optional -- the great circle
-- between the two coordinate pairs IS the distance, and a column of hand-typed numbers
-- saying the same thing would be a hundred more chances to be wrong, and a hundred rows to
-- remember when a waypoint moves.
--
-- The override exists for the legs that are not straight, and they are exactly the ones a
-- glance at a chart identifies: a strait that winds (the Bosphorus is seventeen miles of
-- river bends), a canal, a river.
--
-- Symmetric and stored in both directions, the same choice trade_area_distances made and for
-- the same reason: a lookup is then one indexed read rather than an OR over two columns, and
-- the seed writes the mirror from a single list.
CREATE TABLE public.sea_legs (
    from_waypoint_id bigint NOT NULL,
    to_waypoint_id bigint NOT NULL,

    distance_nm numeric(7,1),

    notes text,

    PRIMARY KEY (from_waypoint_id, to_waypoint_id),
    CONSTRAINT sea_legs_from_fkey FOREIGN KEY (from_waypoint_id)
        REFERENCES public.sea_waypoints(id) ON DELETE CASCADE,
    CONSTRAINT sea_legs_to_fkey FOREIGN KEY (to_waypoint_id)
        REFERENCES public.sea_waypoints(id) ON DELETE CASCADE,
    CONSTRAINT sea_legs_not_self CHECK (from_waypoint_id <> to_waypoint_id)
);


-- ---------------------------------------------------------------------------
-- 3. Where the berth is, and how it reaches the network
-- ---------------------------------------------------------------------------
-- Five decimal places is about a metre, which is far more than a ballast estimate needs and
-- is simply how a coordinate is written; nothing reads past the second.
--
-- Nullable, like every fact on a vessel record and for the same reason: null is "not on
-- file", and a port without coordinates falls back to the area table exactly as it does
-- today. V19 places the ports this desk works and leaves the rest to whoever knows them.
ALTER TABLE public.ports
    ADD COLUMN latitude numeric(8,5),
    ADD COLUMN longitude numeric(8,5),

    -- ISO 3166-1 alpha-2. Not decoration: it is how "Tripoli" gets disambiguated on screen,
    -- and how a parsed "Casablanca, Morocco" is confirmed rather than assumed. Two letters
    -- rather than a name, so it cannot drift into three spellings of one country.
    ADD COLUMN country character varying(2),

    -- The open-water point this berth is reached from. The distance to it is the great
    -- circle from the coordinates above, which is right for a coastal port sitting a few
    -- miles off the lane and wrong for one 250 miles up a river -- hence the override below.
    ADD COLUMN gateway_waypoint_id bigint,

    -- The real distance from the berth to its gateway, where the straight line is not it.
    -- Rostov is up the Don, Izmail is up the Danube, Kiev is up the Dnieper, and the great
    -- circle understates every one of them by a factor of two. There is no shape a
    -- coordinate pair could take that would say so.
    ADD COLUMN gateway_nm numeric(7,1);

ALTER TABLE public.ports
    ADD CONSTRAINT ports_gateway_waypoint_fkey FOREIGN KEY (gateway_waypoint_id)
        REFERENCES public.sea_waypoints(id) ON DELETE SET NULL;

CREATE INDEX ix_ports_gateway ON public.ports USING btree (gateway_waypoint_id);
