-- Every email that raised the same question about one hull.
--
-- A VESSEL_FIELDS item asks "the record says one thing and the mail says another - which?".
-- That question is about a vessel, not about an email, and several emails ask it: a broker
-- re-sends his position list on Monday and again on Wednesday, two brokers carry the same
-- ship, and each arrival produced its own review item. The suppression that was meant to stop
-- that compared the two sets of disagreements exactly, so a hull came back twice over one
-- reworded word - FOX, whose type read "GENERAL-DRY CARGO VESSEL / DOUBLE SKIN/BOX" in one
-- list and "GENERAL-DRY CARGO VESSEL" in the next, with every other figure identical.
--
-- So the item becomes the question and the arrivals become rows here, which is exactly the
-- shape cargo_sources already has and for the same reason: a cargo is one record several
-- brokers describe, and so is a disagreement about a ship. What it buys beyond one row in the
-- queue is the two things a reviewer actually wants - every original email readable from the
-- item, and every sending firm available to attach to the hull.
--
-- Only pending items merge. Once a question has been answered it is history, and a new email
-- disagreeing again is a new question.

CREATE TABLE public.intake_item_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    intake_item_id bigint NOT NULL,
    CONSTRAINT intake_item_sources_item_fkey FOREIGN KEY (intake_item_id)
        REFERENCES public.intake_items(id) ON DELETE CASCADE,

    -- The parse this arrival came from. CASCADE rather than SET NULL, unlike the message
    -- below: a source row exists to say "this parse contributed", and without the parse it
    -- says nothing. parsed_emails is this app's own record and is not emptied behind it.
    parsed_email_id bigint NOT NULL,
    CONSTRAINT intake_item_sources_parsed_fkey FOREIGN KEY (parsed_email_id)
        REFERENCES public.parsed_emails(id) ON DELETE CASCADE,

    -- SET NULL, matching cargo_sources: mail_messages mirrors a server whose folders get
    -- emptied, and the fact that a broker raised this outlives the copy of their email.
    mail_message_id bigint,
    CONSTRAINT intake_item_sources_message_fkey FOREIGN KEY (mail_message_id)
        REFERENCES public.mail_messages(id) ON DELETE SET NULL,

    -- Who sent it. The reason the reviewer can attach more than one firm to the hull: two
    -- brokers on the same ship is the ordinary case, and both are worth keeping.
    reported_by_company_id bigint,
    CONSTRAINT intake_item_sources_company_fkey FOREIGN KEY (reported_by_company_id)
        REFERENCES public.companies(id) ON DELETE SET NULL,

    -- When they told us. The newest row is which reading the item's figures came from.
    reported_at timestamp with time zone DEFAULT now() NOT NULL,

    created_at timestamp with time zone DEFAULT now()
);

-- One row per item per parse. Re-parsing a message cannot double up its sources; a broker who
-- sends a second email is a second row, which is correct - that is a second arrival.
CREATE UNIQUE INDEX ux_intake_item_sources_item_parsed
    ON public.intake_item_sources USING btree (intake_item_id, parsed_email_id);

CREATE INDEX ix_intake_item_sources_item
    ON public.intake_item_sources USING btree (intake_item_id, reported_at DESC);

-- Every item that already exists gets the source it was raised from, so the read path has one
-- shape rather than two. Without this an item created before today would show no origin at all
-- - the drawer reads the sources, not the column.
INSERT INTO public.intake_item_sources
    (intake_item_id, parsed_email_id, mail_message_id, reported_by_company_id, reported_at)
SELECT i.id,
       i.parsed_email_id,
       pe.mail_message_id,
       mm.company_id,
       COALESCE(mm.sent_at, mm.received_at, now())
FROM public.intake_items i
JOIN public.parsed_emails pe ON pe.id = i.parsed_email_id
LEFT JOIN public.mail_messages mm ON mm.id = pe.mail_message_id;
