-- The Feed tab: outside sources read on a timer, and the local model's summaries of them.
--
-- The desk wants the market as it is talked about - freight direction, rates in $/t, which
-- cargoes are moving and which are stuck - and that talk is spread over Telegram channels,
-- trade-press RSS feeds and a couple of public boards where brokers paste their circulars.
-- None of it is a record of anything this app owns, so none of it is audited: the rows here
-- are a machine copying other people's pages, and a summary is a document about them.
--
-- Everything here reads on every deployment and edits on every deployment - sources, topics
-- and summaries are plain rows in the one shared database. Only fetching and summarising are
-- local (FEED_ANALYSIS_ENABLED), because only the office has the model.

CREATE TABLE public.feed_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,

    -- How it is read. TELEGRAM and RSS follow one general rule each; WEBSITE hands the page to
    -- the parser named in parser_key, because a site that is not a feed has no general rule.
    kind varchar(20) NOT NULL,
    CONSTRAINT feed_sources_kind_check CHECK (kind IN ('TELEGRAM', 'RSS', 'WEBSITE')),

    url varchar(1000) NOT NULL,
    parser_key varchar(50),
    CONSTRAINT feed_sources_parser_check CHECK (kind <> 'WEBSITE' OR parser_key IS NOT NULL),

    enabled boolean DEFAULT true NOT NULL,

    -- The validators of the last full answer, sent back as If-None-Match / If-Modified-Since so
    -- an unchanged board or feed costs a 304 rather than a page.
    etag varchar(500),
    last_modified varchar(100),

    last_fetched_at timestamp with time zone,
    last_error text,
    last_new_items integer,

    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE UNIQUE INDEX ux_feed_sources_url ON public.feed_sources USING btree (url);

CREATE TABLE public.feed_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- CASCADE: a source removed is a source whose items nobody asked to keep. Disabling is how
    -- a source stops without losing what it collected.
    source_id bigint NOT NULL,
    CONSTRAINT feed_items_source_fkey FOREIGN KEY (source_id)
        REFERENCES public.feed_sources(id) ON DELETE CASCADE,

    -- The source's own identity for the item: an RSS guid, a Telegram post number, an offer's
    -- uuid, or a hash where the page offers none. The dedupe key, per source.
    external_id varchar(500) NOT NULL,

    published_at timestamp with time zone,
    title varchar(500),
    text text NOT NULL,
    url varchar(1000),
    author varchar(300),

    -- sha-256 of the normalised text. Lets the summariser drop the same circular pasted onto
    -- two boards without comparing every pair of bodies.
    content_hash varchar(64) NOT NULL,

    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX ux_feed_items_source_external
    ON public.feed_items USING btree (source_id, external_id);
CREATE INDEX ix_feed_items_published ON public.feed_items USING btree (published_at DESC);

CREATE TABLE public.feed_topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    -- Comma-separated. What an item has to mention to be read for this topic at all.
    keywords text,
    -- Whether "Summarise" runs it. Kept rather than deleted so a topic can rest for a week.
    selected boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE UNIQUE INDEX ux_feed_topics_name ON public.feed_topics USING btree (lower(name));

CREATE TABLE public.feed_summaries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- One press of Summarise. Every topic it ran shares the id.
    run_id uuid NOT NULL,

    -- SET NULL, with the name kept beside it: a summary is history and outlives its topic.
    topic_id bigint,
    CONSTRAINT feed_summaries_topic_fkey FOREIGN KEY (topic_id)
        REFERENCES public.feed_topics(id) ON DELETE SET NULL,
    topic_name varchar(200) NOT NULL,

    status varchar(20) NOT NULL,
    CONSTRAINT feed_summaries_status_check CHECK (status IN ('RUNNING', 'DONE', 'FAILED')),

    content text,

    -- How what was collected was made to fit the model's window, and what that cost.
    strategy varchar(20),
    CONSTRAINT feed_summaries_strategy_check
        CHECK (strategy IS NULL OR strategy IN ('SINGLE_PASS', 'MAP_REDUCE')),
    levels integer,
    llm_calls integer,
    items_considered integer,
    items_used integer,
    -- Items that matched but did not fit under the call cap. Stored and printed, so a summary
    -- never quietly covers less than was collected.
    items_dropped integer,
    prompt_tokens integer,
    completion_tokens integer,
    context_window integer,

    period_from timestamp with time zone,
    period_to timestamp with time zone,

    -- The prompt as it was when this ran. The editable one moves on; this one explains the row.
    system_prompt text,
    model varchar(300),
    error text,
    duration_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX ix_feed_summaries_created ON public.feed_summaries USING btree (created_at DESC);
CREATE INDEX ix_feed_summaries_topic ON public.feed_summaries USING btree (topic_id, created_at DESC);

-- Which items a summary was written from, so "where did that rate come from" has an answer.
CREATE TABLE public.feed_summary_items (
    summary_id bigint NOT NULL,
    CONSTRAINT feed_summary_items_summary_fkey FOREIGN KEY (summary_id)
        REFERENCES public.feed_summaries(id) ON DELETE CASCADE,
    item_id bigint NOT NULL,
    CONSTRAINT feed_summary_items_item_fkey FOREIGN KEY (item_id)
        REFERENCES public.feed_items(id) ON DELETE CASCADE,
    PRIMARY KEY (summary_id, item_id)
);

CREATE INDEX ix_feed_summary_items_item ON public.feed_summary_items USING btree (item_id);
