-- What a person has already settled about a hull, so the queue stops asking it again.
--
-- Two tables, two different repeats, both observed on this desk every morning.
--
--
-- intake_field_decisions: "her bale is 291,000, not 8,240."
--
-- ANGORA re-sends the same position list daily. Its reading of JELENA disagreed with the
-- record about one figure, the reviewer answered it, and the next morning the identical email
-- raised the identical question - because the answer was written on the item, and the item was
-- closed. Nothing recorded that this value, from this correspondent, about this field, had
-- been looked at and turned down.
--
-- Only a decision that leaves a disagreement standing is worth a row. Accepting the email
-- writes its figure to the record, so tomorrow there is nothing to disagree about; keeping
-- what was on file, or correcting to a third value, leaves the email as wrong tomorrow as it
-- was today, and that is what this suppresses.
--
-- Scoped to the correspondent on purpose. That ANGORA is wrong about her bale says nothing
-- about what the next broker reports, and a second firm carrying the same figure is a second
-- opinion the desk has not heard yet. The value is stored canonically - the figure as it was
-- compared, without its unit - so it can be compared back with the same tolerance the diff
-- uses rather than as display text.
--
--
-- intake_vessel_aliases: "when Interscan writes PHANTOM they mean hull 4607."
--
-- Two hulls on this desk are called PHANTOM and neither carries an IMO, so findByExactName
-- returns two rows and the resolver treats that as no match at all - correctly, because
-- picking whichever came first would file one owner's position on another owner's ship. The
-- reviewer linked Interscan's PHANTOM to the right hull on the 10th, the 14th and the 15th,
-- and the 16th asked again. Linking could record nothing: vessel_ex_names files the name the
-- email used, and here that name is the one she already carries, so there was nothing to file.
--
-- This is deliberately not a former name and must not be folded into that table. A former name
-- is a fact about the ship - she used to be called that, and it is true for everyone. This is a
-- fact about one correspondent's vocabulary, and it is the only thing that can settle a name
-- two hulls share: PHANTOM is ambiguous in the fleet and unambiguous in Interscan's list.
--
-- One hull per firm per name, replaced rather than duplicated when a firm starts meaning a
-- different ship by it - an owner sells one and takes the name to the next, and the later
-- statement is the one to act on.

CREATE TABLE public.intake_field_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vessel_id bigint NOT NULL,
    CONSTRAINT intake_field_decisions_vessel_fkey FOREIGN KEY (vessel_id)
        REFERENCES public.vessels(id) ON DELETE CASCADE,

    -- The entity property name, as VesselFieldDiff names it and an accept request sends it.
    field character varying(60) NOT NULL,

    -- Who reported the value that was turned down. Nullable, because the mail sync cannot
    -- always put an address to a firm, and a decision about an unidentified sender is still
    -- worth keeping - it is the same address writing again tomorrow.
    reported_by_company_id bigint,
    CONSTRAINT intake_field_decisions_company_fkey FOREIGN KEY (reported_by_company_id)
        REFERENCES public.companies(id) ON DELETE CASCADE,

    -- The email's figure as it was compared: no unit, no thousands separator, capacities
    -- already in cubic metres. Text rather than a typed column because one table serves a
    -- deadweight, an ice class and a boolean.
    value_text text NOT NULL,

    -- What was done instead, for the screen that explains why a figure is not being offered.
    -- KEPT (the record was right) or CORRECTED (neither side was).
    decision character varying(20) NOT NULL,

    -- Only on CORRECTED: what the reviewer put there instead.
    corrected_to text,

    intake_item_id bigint,
    CONSTRAINT intake_field_decisions_item_fkey FOREIGN KEY (intake_item_id)
        REFERENCES public.intake_items(id) ON DELETE SET NULL,

    decided_at timestamp with time zone DEFAULT now() NOT NULL,
    decided_by character varying(255)
);

-- One decision per firm per field per value. A pair of partial indexes rather than one over a
-- nullable column: Postgres counts NULLs as distinct, so a single index would let an
-- unidentified sender accumulate a row a day - precisely the repeat this table exists to stop.
CREATE UNIQUE INDEX ux_intake_field_decisions_company
    ON public.intake_field_decisions USING btree (vessel_id, field, reported_by_company_id, value_text)
    WHERE reported_by_company_id IS NOT NULL;

CREATE UNIQUE INDEX ux_intake_field_decisions_no_company
    ON public.intake_field_decisions USING btree (vessel_id, field, value_text)
    WHERE reported_by_company_id IS NULL;

-- How the sweep asks the question: everything settled about this hull, then matched in memory.
-- A hull has a handful of these at most, so one indexed read beats a query per field.
CREATE INDEX ix_intake_field_decisions_vessel
    ON public.intake_field_decisions USING btree (vessel_id);


CREATE TABLE public.intake_vessel_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vessel_id bigint NOT NULL,
    CONSTRAINT intake_vessel_aliases_vessel_fkey FOREIGN KEY (vessel_id)
        REFERENCES public.vessels(id) ON DELETE CASCADE,

    -- Required, unlike the decisions above: an alias with no correspondent behind it is a
    -- claim about the name itself, which is what vessel_ex_names is for. Without a firm to
    -- scope it, resolving PHANTOM this way would be the arbitrary pick the resolver refuses.
    reported_by_company_id bigint NOT NULL,
    CONSTRAINT intake_vessel_aliases_company_fkey FOREIGN KEY (reported_by_company_id)
        REFERENCES public.companies(id) ON DELETE CASCADE,

    -- As the email spelled it, for a screen to print.
    name character varying(255) NOT NULL,

    -- Folded for lookup, the way port_aliases.alias_key is and for the same reason: the
    -- comparison lives in one place instead of in every query that needs it.
    name_key character varying(255) NOT NULL,

    -- LINKED (pointed at a hull on file) or CREATED (the reviewer made her from this email).
    source character varying(20) NOT NULL,

    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by character varying(255)
);

-- One hull per firm per name. A firm that starts meaning a different ship by a name replaces
-- its own row rather than adding a second, which would put the resolver back where it started.
CREATE UNIQUE INDEX ux_intake_vessel_aliases_company_name
    ON public.intake_vessel_aliases USING btree (reported_by_company_id, name_key);

CREATE INDEX ix_intake_vessel_aliases_vessel
    ON public.intake_vessel_aliases USING btree (vessel_id);
