-- Three repeats the queue was still asking, and what it needs to stop asking them.
--
-- Measured on the live queue on 2026-09-24: 111 CARGO_MERGE items over 39 cargoes (cargo 122
-- asked seven times, six of them by a broker already on it as a source); COMPANY_DETAILS rows
-- carrying thirteen emails for "1 field differs"; CARLOW raised seven times over two figures,
-- answered one way and then back again as each broker's list arrived.
--
--
-- intake_items.minor: "for the record, not for the queue".
--
-- A question that is real but not urgent - a firm's website moved, a deadweight rounded 1%
-- differently, a figure the desk has already turned down arriving from a second broker - is
-- still kept, and still answered by the same drawer, but it is not what "Needs review" counts.
-- It waits on its own sub-tab and, for a company, behind a button on the company's own record.
-- A flag rather than a status, because it is recomputed as arrivals merge in: a minor company
-- question becomes a major one the day a new email address turns up in the signature.
ALTER TABLE public.intake_items
    ADD COLUMN minor boolean DEFAULT false NOT NULL;

CREATE INDEX ix_intake_items_pending_minor
    ON public.intake_items USING btree (minor, kind)
    WHERE status = 'PENDING';


-- intake_field_decisions.replaced_value: what the record held before an answer moved it.
--
-- The table stored only answers that left a disagreement standing (KEPT, CORRECTED). That
-- stopped one broker re-asking, and did nothing for the flip: GN says built 2005, the desk
-- accepts it over 2004; Eksen's list still says 2004 and raises the same pair the other way
-- round. The desk has weighed exactly those two values already. ACCEPTED rows are now written
-- too, and every answer that moved the record says from what, so "the desk moved away from
-- this value" is a question with an answer.
ALTER TABLE public.intake_field_decisions
    ADD COLUMN replaced_value text;


-- vessel_field_reports: every figure every firm has told us about a hull, agreeing or not.
--
-- A decision says what the desk did; this says what the market says. One row per hull, field,
-- firm and value - not per email, since a daily list would otherwise write the same row every
-- morning - with the first and last time it was heard and how often. It is what lets a
-- disagreement be weighed rather than merely detected: three firms reporting what is on file
-- against one reporting something else is not the same question as one broker correcting a
-- record nobody has confirmed, and a value the desk turned down that two more firms have since
-- reported is not the same as one broker repeating himself.
--
-- Values are canonical, as in intake_field_decisions: the figure as compared, no unit, a
-- capacity already in cubic metres.
CREATE TABLE public.vessel_field_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vessel_id bigint NOT NULL,
    CONSTRAINT vessel_field_reports_vessel_fkey FOREIGN KEY (vessel_id)
        REFERENCES public.vessels(id) ON DELETE CASCADE,

    field character varying(60) NOT NULL,

    -- Nullable for the reason the decisions' column is: the sync cannot always place a sender,
    -- and an unplaced address writing every morning is still one voice rather than none.
    reported_by_company_id bigint,
    CONSTRAINT vessel_field_reports_company_fkey FOREIGN KEY (reported_by_company_id)
        REFERENCES public.companies(id) ON DELETE CASCADE,

    value_text text NOT NULL,

    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    times_seen integer DEFAULT 1 NOT NULL,

    last_parsed_email_id bigint,
    CONSTRAINT vessel_field_reports_parsed_fkey FOREIGN KEY (last_parsed_email_id)
        REFERENCES public.parsed_emails(id) ON DELETE SET NULL
);

-- Partial pair for the same reason as V25's: NULLs are distinct to a unique index, and an
-- unplaced sender would otherwise gain a row a day.
CREATE UNIQUE INDEX ux_vessel_field_reports_company
    ON public.vessel_field_reports USING btree (vessel_id, field, reported_by_company_id, value_text)
    WHERE reported_by_company_id IS NOT NULL;

CREATE UNIQUE INDEX ux_vessel_field_reports_no_company
    ON public.vessel_field_reports USING btree (vessel_id, field, value_text)
    WHERE reported_by_company_id IS NULL;

CREATE INDEX ix_vessel_field_reports_vessel
    ON public.vessel_field_reports USING btree (vessel_id);


-- One pending CARGO_MERGE per cargo, as V21 did for vessels.
--
-- IntakeService now folds another sighting of the same candidate into the question already
-- waiting; this does the same for the ones already queued. The newest item survives - its
-- payload is the newest reading, which is the one a merge would fill from - and every other
-- item's arrivals move onto it, so no broker who sent the cargo goes missing whichever way it
-- is answered. Only pending items: an answered one is a record of a decision.
UPDATE public.intake_item_sources s
SET intake_item_id = keep.keep_id
FROM (
    SELECT i.id AS loser_id,
           (SELECT max(i2.id) FROM public.intake_items i2
            WHERE i2.cargo_id = i.cargo_id
              AND i2.kind = 'CARGO_MERGE'
              AND i2.status = 'PENDING') AS keep_id
    FROM public.intake_items i
    WHERE i.kind = 'CARGO_MERGE'
      AND i.status = 'PENDING'
      AND i.cargo_id IS NOT NULL
) keep
WHERE s.intake_item_id = keep.loser_id
  AND keep.loser_id <> keep.keep_id
  AND NOT EXISTS (
      SELECT 1 FROM public.intake_item_sources other
      WHERE other.intake_item_id = keep.keep_id
        AND other.parsed_email_id = s.parsed_email_id
  );

DELETE FROM public.intake_item_sources s
USING public.intake_items i
WHERE s.intake_item_id = i.id
  AND i.kind = 'CARGO_MERGE'
  AND i.status = 'PENDING'
  AND i.cargo_id IS NOT NULL
  AND i.id < (SELECT max(i2.id) FROM public.intake_items i2
              WHERE i2.cargo_id = i.cargo_id
                AND i2.kind = 'CARGO_MERGE'
                AND i2.status = 'PENDING');

DELETE FROM public.intake_items i
WHERE i.kind = 'CARGO_MERGE'
  AND i.status = 'PENDING'
  AND i.cargo_id IS NOT NULL
  AND i.id < (SELECT max(i2.id) FROM public.intake_items i2
              WHERE i2.cargo_id = i.cargo_id
                AND i2.kind = 'CARGO_MERGE'
                AND i2.status = 'PENDING');
