-- Accounts, and the desks they belong to.
--
-- Until now there was one credential, held in the environment, and nothing in the database
-- knew who anybody was. That stops being enough the moment a second desk shares the
-- deployment: each person logs in as themselves, and what they can see is decided by the
-- desk (tenant) they belong to.
--
-- Tenant 1 is created here and is the desk this database already holds. Every row that
-- exists today belongs to it - the migrations that add tenant_id to the business tables
-- backfill to 1 - so an existing deployment upgrades into a one-tenant installation that
-- behaves exactly as before.
--
-- No user is inserted. A password hash cannot be produced in SQL without inventing one, so
-- the first account is created by the application at startup from AUTH_USERNAME and
-- AUTH_PASSWORD / AUTH_PASSWORD_HASH (UserBootstrap), the same variables that used to be the
-- only credential. After that the environment no longer decides any password.
CREATE TABLE public.tenants (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(200) NOT NULL,
    status      varchar(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_tenants_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

CREATE UNIQUE INDEX ux_tenants_name ON public.tenants (lower(name));

INSERT INTO public.tenants (id, name) VALUES (1, 'Default desk');
SELECT setval(pg_get_serial_sequence('public.tenants', 'id'), 1);

-- A login name is unique across the whole installation, not per tenant. That is what lets
-- the login screen stay two fields: with names unique per desk, somebody would have to say
-- which desk they are before saying who they are.
--
-- The lockout counters live on the row rather than in memory: they survive a restart, and
-- one person mistyping does not lock everybody else out, which a single counter did.
--
-- token_version is what makes a stateless token revocable where it matters. It is carried in
-- every token and compared on every request; disabling an account, resetting its password or
-- changing its role bumps it, and every token issued before that stops working at once.
CREATE TABLE public.users (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             bigint       NOT NULL REFERENCES public.tenants (id),
    username              varchar(150) NOT NULL,
    display_name          varchar(200),
    password_hash         varchar(100) NOT NULL,
    role                  varchar(20)  NOT NULL,
    enabled               boolean      NOT NULL DEFAULT true,
    must_change_password  boolean      NOT NULL DEFAULT false,
    failed_attempts       integer      NOT NULL DEFAULT 0,
    locked_until          timestamptz,
    token_version         integer      NOT NULL DEFAULT 0,
    last_login_at         timestamptz,
    created_at            timestamptz  NOT NULL DEFAULT now(),
    created_by            varchar(150),
    CONSTRAINT ck_users_role CHECK (role IN ('PLATFORM_ADMIN', 'TENANT_ADMIN', 'USER'))
);

CREATE UNIQUE INDEX ux_users_username ON public.users (lower(username));
CREATE INDEX ix_users_tenant ON public.users (tenant_id);
