-- A mailbox per person.
--
-- The market data a desk works from is shared by the desk; a mailbox is not. Each person reads
-- their own inbox on the Mailbox tab, files it into their own folders by their own rules, and
-- replies from their own address. What the parser reads out of anybody's mail - a cargo, a
-- position, a question for Intake - still lands in the desk's shared tables, which is the
-- point of reading it.
--
-- owner_user_id is nullable here only because the rows that exist were written before there
-- were people to own them, and V32 can run before the first account exists (V30-V32 arriving
-- in one deploy run before the application creates it). The application assigns those rows to
-- the account the environment's mailbox belongs to at startup (MailOwnership), and writes an
-- owner on every new row.

CREATE TABLE public.mail_accounts (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        bigint       NOT NULL REFERENCES public.tenants (id),
    user_id          bigint       NOT NULL REFERENCES public.users (id),
    -- The address, the IMAP/SMTP login and the From of everything sent: one mailbox, one
    -- identity. Providers refuse a From the login does not own, so they are not separate.
    email_address    varchar(255) NOT NULL,
    display_name     varchar(200),
    imap_host        varchar(255) NOT NULL,
    imap_port        integer      NOT NULL DEFAULT 993,
    imap_ssl         boolean      NOT NULL DEFAULT true,
    smtp_host        varchar(255) NOT NULL,
    smtp_port        integer      NOT NULL DEFAULT 465,
    -- AES-GCM under CREDENTIALS_KEY (CredentialCipher). Never returned by the API.
    password_enc     text         NOT NULL,
    enabled          boolean      NOT NULL DEFAULT true,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    updated_at       timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_mail_accounts_user ON public.mail_accounts (user_id);
CREATE INDEX ix_mail_accounts_tenant ON public.mail_accounts (tenant_id);

DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'mail_messages', 'mail_folders', 'mail_rules',
        'mail_server_folders', 'mail_sync_state', 'mail_replies'
    ] LOOP
        EXECUTE format('ALTER TABLE public.%I ADD COLUMN owner_user_id bigint REFERENCES public.users (id)', t);
        EXECUTE format('CREATE INDEX %I ON public.%I (owner_user_id)', 'ix_' || t || '_owner', t);
    END LOOP;
END $$;

-- Two people on one desk are often on the same circular, and each must find it in their own
-- inbox; the dedupe that stopped one mailbox storing it twice is now per mailbox.
DROP INDEX public.ux_mail_messages_message_id;
CREATE UNIQUE INDEX ux_mail_messages_message_id
    ON public.mail_messages (tenant_id, coalesce(owner_user_id, 0), message_id)
    WHERE message_id IS NOT NULL;

DROP INDEX public.ux_mail_messages_uid;
CREATE UNIQUE INDEX ux_mail_messages_uid
    ON public.mail_messages (tenant_id, coalesce(owner_user_id, 0), imap_folder, imap_validity, imap_uid)
    WHERE imap_uid IS NOT NULL;

DROP INDEX public.ux_mail_folders_name;
CREATE UNIQUE INDEX ux_mail_folders_name
    ON public.mail_folders (tenant_id, coalesce(owner_user_id, 0), lower((name)::text));

DROP INDEX public.ux_mail_rules_name;
CREATE UNIQUE INDEX ux_mail_rules_name
    ON public.mail_rules (tenant_id, coalesce(owner_user_id, 0), lower((name)::text));

-- The two tables keyed by a folder name: everybody has an INBOX. A surrogate key, because the
-- owner cannot be part of a primary key while it may still be null.
ALTER TABLE public.mail_server_folders DROP CONSTRAINT mail_server_folders_pkey;
ALTER TABLE public.mail_server_folders ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
CREATE UNIQUE INDEX ux_mail_server_folders_name
    ON public.mail_server_folders (tenant_id, coalesce(owner_user_id, 0), full_name);

ALTER TABLE public.mail_sync_state DROP CONSTRAINT mail_sync_state_pkey;
ALTER TABLE public.mail_sync_state ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
CREATE UNIQUE INDEX ux_mail_sync_state_folder
    ON public.mail_sync_state (tenant_id, coalesce(owner_user_id, 0), imap_folder);
