-- Which boards a desk reads into Intake is the desk's choice.
--
-- feed_sources.into_intake was one switch for the installation, which meant one desk's choice
-- for every desk: either all of them spent GPU parsing a board, or none got its circulars. The
-- sources themselves stay global - a page is fetched once for everybody - and what moves to the
-- desk is the decision to send its posts through the parser.
--
-- Desk 1 keeps exactly the boards it had marked. The column goes in the same migration, so
-- there is never a moment with two answers to the question.
CREATE TABLE public.feed_intake_subscriptions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       bigint      NOT NULL REFERENCES public.tenants (id),
    -- Deleting a source takes its subscriptions with it; FeedSourceService refuses while any
    -- desk still has an unanswered question from it.
    feed_source_id  bigint      NOT NULL REFERENCES public.feed_sources (id) ON DELETE CASCADE,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_feed_intake_subscriptions ON public.feed_intake_subscriptions (tenant_id, feed_source_id);

INSERT INTO public.feed_intake_subscriptions (tenant_id, feed_source_id)
SELECT 1, id FROM public.feed_sources WHERE into_intake;

ALTER TABLE public.feed_sources DROP COLUMN into_intake;
