-- A Brevo account per person.
--
-- Until now there was one key, BREVO_API_KEY in the environment, and it was the default desk's:
-- every other desk was told it had no Brevo route. Circulars are sent per person (V33) and a
-- mailbox is per person (V32), so the key follows them - each person saves their own on
-- Settings > My mailbox, and the environment's key stays with the account that owns the
-- environment's mailbox (MAILBOX_OWNER), the person it was set up for.
--
-- The sender is beside the key because a Brevo From is not the mailbox's to decide: it must be
-- a sender verified on that Brevo account, and somebody with a key and no mailbox of their own
-- otherwise has no From at all. Null falls back to the mailbox address.
--
-- No rows to move, so no app.rls_bypass: the table starts empty and the application fills it.

CREATE TABLE public.brevo_accounts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       bigint       NOT NULL REFERENCES public.tenants (id),
    user_id         bigint       NOT NULL REFERENCES public.users (id),
    -- AES-GCM under CREDENTIALS_KEY (CredentialCipher). Never returned by the API.
    api_key_enc     text         NOT NULL,
    -- The last four characters, so the screen can say which key is stored without holding it.
    key_hint        varchar(8)   NOT NULL,
    sender_address  varchar(255),
    sender_name     varchar(200),
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_brevo_accounts_user ON public.brevo_accounts (user_id);
CREATE INDEX ix_brevo_accounts_tenant ON public.brevo_accounts (tenant_id);

-- The same wall V36 put round every desk table.
ALTER TABLE public.brevo_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brevo_accounts FORCE ROW LEVEL SECURITY;
CREATE POLICY desk_rows ON public.brevo_accounts
    USING (current_setting('app.rls_bypass', true) = 'on'
           OR tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (current_setting('app.rls_bypass', true) = 'on'
           OR tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint);
