-- Who changed what, when, and what it was before.
--
-- One table for every audited entity rather than a shadow table per entity. The question
-- this is here to answer is "what happened to this record" and, more often, "what changed
-- at all recently" - and the second one is a UNION across twelve tables in the per-entity
-- design and a single ORDER BY here. Per-entity shadow tables win when you want to SELECT a
-- whole row as it stood on a date; that is not what gets asked here, and it costs a
-- migration per entity forever after.
--
-- Two row shapes live in this table, told apart by field_name:
--
--   field_name IS NOT NULL - one changed field of an update. old_value and new_value are
--                            that field's values, and there is one such row per field that
--                            actually changed in the save.
--   field_name IS NULL     - a whole record appearing or disappearing. A create puts the
--                            new row's fields in new_value as JSON; a delete puts the dead
--                            row's fields in old_value the same way.
--
-- The asymmetry is deliberate. An update is read as a sentence - "working: true -> false" -
-- and splitting it per field is what makes that readable and what makes a single field
-- revertible. A create has no before, so per-field rows would be a column of nulls; and a
-- delete needs every column it had in one place, or nothing could ever put it back.


CREATE TABLE public.data_changes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- All the rows written by one transaction share this. It is what makes a change set a
    -- unit: an import of eighty contacts is one id, and so is a single Save that touched a
    -- person and two of their addresses. Generated in the application, not here, because
    -- the value has to be known before the first row of the set is written.
    change_set uuid NOT NULL,

    -- The entity as the API names it - 'company', 'person', 'contact' - not the Java class
    -- and not the table. It is what the URL and the filter use, so storing anything else
    -- would mean translating on every read.
    entity_type character varying(40) NOT NULL,
    entity_id bigint NOT NULL,

    -- What the record was called when it changed. Denormalised on purpose, and the one
    -- piece of denormalisation here that earns its keep: for a deleted record there is
    -- nothing left to join to, and a history screen listing "contact 4127 deleted" with no
    -- way to find out which address that was is a history screen nobody reads twice.
    entity_label character varying(255),

    operation character varying(6) NOT NULL,
    CONSTRAINT data_changes_operation_check
        CHECK (operation IN ('create', 'update', 'delete')),

    -- The Java property name, which is also the name the API and the forms use. Null for a
    -- create or a delete - see the note on row shapes above.
    field_name character varying(64),

    -- Text, not jsonb, and not a typed column per kind of value. Everything in here is
    -- being kept to be read back by a human or written back to exactly the field it came
    -- from, and neither of those wants a type. A number stored as '4' and a date stored as
    -- an ISO string both come back as what they were; the revert converts them using the
    -- field's own type, which is the only place that knows it.
    old_value text,
    new_value text,

    changed_at timestamp with time zone NOT NULL,
    -- The logged-in username. Nullable because a change can be made by something with no
    -- user behind it - a scheduled sync, a startup fixup - and recording 'system' for those
    -- would be inventing an account that does not exist.
    changed_by character varying(255),

    -- Why, when something bothered to say: 'Import of contacts-2026-08-23.csv'. Set per
    -- transaction, so every row of a change set carries the same one.
    context character varying(255)
);


-- The record's own history, newest first. Covers the drawer tab and the entity filter on
-- the history page, which are the same query with and without a LIMIT.
CREATE INDEX ix_data_changes_entity
    ON public.data_changes USING btree (entity_type, entity_id, id DESC);

-- "What changed recently", the default view with no filter set.
CREATE INDEX ix_data_changes_changed_at
    ON public.data_changes USING btree (changed_at DESC);

-- Pulling one change set back out whole, which is what "show me everything that import
-- did" is.
CREATE INDEX ix_data_changes_change_set
    ON public.data_changes USING btree (change_set);
