-- Replying to synced mail from inside the app, and what that costs the mailbox's day.
--
-- Two additions, one feature.


-- 1. A second default footer, for replies.
--
-- The footers themselves are already reusable and already have a default; what a reply
-- wants is a *different* one. A circular closes with the desk's marketing block, and a
-- reply to one broker should not - so the flag is per purpose rather than per footer, and
-- one footer may hold both, either, or neither.
--
-- Same partial unique index as is_default, and it has to be: it is what makes "the default"
-- a fact about the table rather than a convention the application remembers to keep.
ALTER TABLE public.email_footers
    ADD COLUMN is_reply_default boolean DEFAULT false NOT NULL;

CREATE UNIQUE INDEX ux_email_footers_single_reply_default
    ON public.email_footers USING btree (is_reply_default) WHERE is_reply_default;


-- 2. What this app has replied.
--
-- Not a row in mail_messages, and the distinction is the point: that table is a mirror of
-- what the server holds, written only by the sync, and a row this app invented would be a
-- message no folder contains. The provider's own copy of this reply lands in the Sent
-- folder and is synced like any other message, in its own time.
--
-- Which is exactly why this table is worth having anyway. It is written the moment the
-- send returns, so the day's count is right immediately rather than at the next poll; it
-- survives a provider that keeps no Sent copy at all; and it is the only place that knows
-- which message a reply was a reply *to*, since In-Reply-To is not among the headers the
-- sync stores.
--
-- Failures are not recorded here. A reply that could not be sent is an error on the screen
-- of the person who wrote it, still holding their text - not history.
CREATE TABLE public.mail_replies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The message replied to. ON DELETE SET NULL rather than CASCADE: the reply happened
    -- whether or not the mail it answered is still on file, and the day's count must not
    -- change because somebody cleaned out an old folder.
    mail_message_id bigint,
    CONSTRAINT mail_replies_mail_message_id_fkey FOREIGN KEY (mail_message_id)
        REFERENCES public.mail_messages(id) ON DELETE SET NULL,

    -- The Message-ID this app put on the reply. Stored so the Sent-folder copy can be
    -- recognised as the same message rather than counted as a second one.
    message_id character varying(998),

    to_address character varying(320) NOT NULL,
    subject text,

    -- What was actually sent, footer and quoted original included, after the merge. The
    -- same reasoning as circulation_runs.composed_html: a reply that cannot be read back
    -- exactly as it went out is a record of the fact and not of the message.
    body_html text NOT NULL,

    -- By name, like the circulation runs record theirs, so history stays truthful after
    -- somebody deletes the footer it used.
    footer_id bigint,
    footer_name character varying(150),

    -- Without a zone, like every other timestamp in the mailbox: the day this is counted
    -- against is the server's local day, and the Sent-folder rows it is read beside carry
    -- the same kind.
    sent_at timestamp without time zone NOT NULL,
    sent_by character varying(255)
);

-- "How many today", which is the only question asked of this table in bulk.
CREATE INDEX ix_mail_replies_sent_at ON public.mail_replies USING btree (sent_at DESC);

-- "Has this been replied to?", asked once per opened message.
CREATE INDEX ix_mail_replies_message ON public.mail_replies USING btree (mail_message_id);
