-- The training corpus: incoming mail kept, labelled, and shaped into finetuning examples
-- that teach a model to read a cargo offer and a vessel opening position.
--
-- ONE TABLE, and the first question it has to answer is why it is not mail_messages.
--
-- mail_messages is a mirror of what the IMAP server holds, written only by the sync. Rows
-- in it come and go with the mailbox: a folder cleaned out on the server, a re-sync after a
-- UIDVALIDITY reset, a retention rule at the provider. A corpus built on top of that would
-- lose examples to housekeeping nobody connected to the dataset, and the annotation - the
-- expensive half, the part a human typed - would go with them.
--
-- So a sample carries its own copy of the text it trains on. The mail_message_id beside it
-- is provenance ("where did this come from"), not storage, and it is ON DELETE SET NULL for
-- exactly that reason: the sample outlives the message.
--
-- The other half of the table is the annotation - what the model is supposed to output for
-- this email. It is text holding JSON rather than jsonb, and that is deliberate: nothing in
-- the app queries into it, the shape is still being worked out, and a shape still moving is
-- one that must not need a migration every time it does. The service validates that it
-- parses before storing it, so the export cannot emit a broken line.
--
-- NOT AUDITED. data_changes records changes somebody made to the business data; this table
-- is a working document, and one capture run writes eighty rows to record that a machine
-- copied eighty emails it already had. Same reasoning that keeps circulation_list_entries
-- out of AuditedEntities.
--
-- THE TABLE IS CREATED EVERYWHERE, INCLUDING WHERE THE FEATURE IS OFF. Flyway builds one
-- schema, not a schema per deployment, and a migration that ran conditionally would make
-- "which columns does this database have" a question with more than one answer. The switch
-- is ANALYSIS_ENABLED at runtime (false on Render); an empty table costs nothing.
CREATE TABLE public.analysis_samples (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Where it came from, if it is still there. Provenance only - everything needed to
    -- train on this sample is in the columns below.
    mail_message_id bigint,
    CONSTRAINT analysis_samples_mail_message_id_fkey FOREIGN KEY (mail_message_id)
        REFERENCES public.mail_messages(id) ON DELETE SET NULL,

    -- MAILBOX = captured from synced mail. PASTED = typed or pasted in by hand, which is
    -- how a corpus gets started on a machine whose IMAP is not configured, and how an
    -- example from somebody else's screenshot gets in at all.
    source character varying(20) DEFAULT 'MAILBOX' NOT NULL,

    -- The RFC Message-ID of the original. The dedupe key, for the same reason it is the
    -- dedupe key in mail_messages: it survives a re-fetch and a re-index, so capturing the
    -- same folder twice adds nothing the second time.
    message_id character varying(998),

    from_address character varying(320),
    from_name character varying(255),
    subject text,
    sent_at timestamp without time zone,
    received_at timestamp without time zone,

    -- The snapshot that is actually trained on. Plain text, never the HTML part: the words
    -- are the same and the markup is noise a model would have to learn to ignore.
    body_text text NOT NULL,

    -- Names only, as in mail_messages. A position list arriving as an attachment is a real
    -- shape, and it is worth seeing that the body was empty because the cargo was in a PDF.
    attachment_names text,

    -- UNLABELLED | CARGO_OFFER | VESSEL_OPENING | BOTH | OTHER. What kind of email this is,
    -- which is the first thing a model has to get right and the coarsest thing to check a
    -- dataset for. BOTH is not a hedge: one broker's circular routinely carries a page of
    -- cargoes and a page of open tonnage.
    label character varying(30) DEFAULT 'UNLABELLED' NOT NULL,

    -- NEW | READY | SKIPPED. A second axis, not a finer label: READY is the human saying
    -- this example is fit to train on, and it is the only status the export reads. SKIPPED
    -- keeps a bad example on file rather than deleting it, so the same junk is not captured
    -- and re-reviewed on every pass.
    status character varying(20) DEFAULT 'NEW' NOT NULL,

    -- The target output: the JSON a model should produce for this email.
    annotation text,

    -- Why this one is odd, in words. Not training data - it is for the person labelling.
    notes text,

    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    created_by character varying(255)
);

-- Dedupe, on both identities and neither of them mandatory. Partial, because a pasted
-- sample has no Message-ID and a sample whose message has been deleted has no id either -
-- and NULLs must not collide with each other.
CREATE UNIQUE INDEX ux_analysis_samples_message_id
    ON public.analysis_samples USING btree (message_id) WHERE message_id IS NOT NULL;

CREATE UNIQUE INDEX ux_analysis_samples_mail_message
    ON public.analysis_samples USING btree (mail_message_id) WHERE mail_message_id IS NOT NULL;

-- The two axes the tab filters and counts on, and the order it lists in.
CREATE INDEX ix_analysis_samples_label ON public.analysis_samples USING btree (label);
CREATE INDEX ix_analysis_samples_status ON public.analysis_samples USING btree (status);
CREATE INDEX ix_analysis_samples_received_at
    ON public.analysis_samples USING btree (received_at DESC);
