-- The vocabulary a position list and a cargo enquiry are both written in.
--
-- WHY THIS IS NOT `regions`. That table looks like it should serve, and cannot: it is a
-- circulation-targeting list, not a geography. Its rows include "Europe ports EXCLUDED",
-- "Israel - no", "Ukraine rivers - banned in Russia" and "Towage + Tugs + Barges" — answers
-- to "who should this circular go to", mixed in with a handful of place names at four
-- different scales. Matching a vessel to a cargo asks a different question ("can she be
-- there in time"), and the answer has to come from something where every row is a place and
-- the rows nest.
--
-- Three tables, because the question has three parts:
--
--   trade_areas             the places, nested: WMED is inside MED
--   trade_area_aliases      the hundred ways a broker writes each one
--   trade_area_distances    how far apart two of them are, in ballast days
--
-- The aliases are the load-bearing half. Nothing in this trade writes an area the same way
-- twice — one week of this mailbox carried "W.MED", "WEST MED", "SPAIN MED" and "W.ITALY"
-- for the same water. A vocabulary without aliases is a dropdown nobody's email fits, and
-- the email parser that lands later has nothing to resolve free text against.


-- ---------------------------------------------------------------------------
-- 1. The places
-- ---------------------------------------------------------------------------
CREATE TABLE public.trade_areas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The short form, and the one the app speaks internally. Uppercase by convention;
    -- unique, so a seed run twice cannot produce two West Meds.
    code character varying(16) NOT NULL,

    name character varying(100) NOT NULL,

    -- Containment, not adjacency: WMED's parent is MED because a vessel open in the West
    -- Med IS in the Med. A cargo asking for MED therefore matches her, and a cargo asking
    -- for EMED does not — that pair is the distance table below, because being next door
    -- is a different fact from being inside.
    --
    -- ON DELETE SET NULL rather than CASCADE: deleting "Mediterranean" must not silently
    -- take every position and cargo filed under West Med with it.
    parent_id bigint,
    CONSTRAINT trade_areas_parent_id_fkey FOREIGN KEY (parent_id)
        REFERENCES public.trade_areas(id) ON DELETE SET NULL,

    -- Dropdown order. Alphabetical puts Adriatic above Black Sea above Continent, which is
    -- three unrelated waters in a row; a broker's eye wants the ranges grouped the way the
    -- market quotes them.
    sort_order integer DEFAULT 0 NOT NULL,

    notes text
);

CREATE UNIQUE INDEX ux_trade_areas_code ON public.trade_areas USING btree (code);
CREATE INDEX ix_trade_areas_parent ON public.trade_areas USING btree (parent_id);


-- ---------------------------------------------------------------------------
-- 2. The ways they are written
-- ---------------------------------------------------------------------------
CREATE TABLE public.trade_area_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    trade_area_id bigint NOT NULL,
    CONSTRAINT trade_area_aliases_area_fkey FOREIGN KEY (trade_area_id)
        REFERENCES public.trade_areas(id) ON DELETE CASCADE,

    -- As a human would type it, punctuation and all. Kept readable so the maintenance
    -- screen shows "W.MED" rather than "WMED" and somebody can tell what it came from.
    alias character varying(100) NOT NULL,

    -- What matching actually compares: the alias with every non-alphanumeric character
    -- removed, uppercased. "W.MED", "W MED", "W-MED" and "w.med" all reduce to WMED, which
    -- is the whole reason this is a lookup table and not a column of strings.
    --
    -- A generated column rather than something a service remembers to set, because the
    -- unique index below is only a guarantee if the database computes the key itself.
    -- upper() and regexp_replace() are both immutable, which is what STORED requires.
    alias_key character varying(100)
        GENERATED ALWAYS AS (upper(regexp_replace(alias, '[^A-Za-z0-9]', '', 'g'))) STORED
);

-- One alias resolves to one area, or the vocabulary is ambiguous — and an ambiguous
-- vocabulary is worse than none, because the parser would silently pick whichever row it
-- read first.
CREATE UNIQUE INDEX ux_trade_area_aliases_key ON public.trade_area_aliases USING btree (alias_key);
CREATE INDEX ix_trade_area_aliases_area ON public.trade_area_aliases USING btree (trade_area_id);


-- ---------------------------------------------------------------------------
-- 3. How far apart they are
-- ---------------------------------------------------------------------------
-- In ballast days, because that is the unit the question is actually asked in. "Is this
-- ship near the cargo" is never answered in miles on a chartering desk; it is answered by
-- whether she can be at the load port inside the laycan, which is her open date plus the
-- ballast leg.
--
-- Deliberately sparse. A full matrix over two dozen areas is six hundred numbers nobody
-- would keep true, and most of them would be guesses about trades this desk does not do.
-- Only pairs a broker here would actually consider are seeded; an unseeded pair is not an
-- error, it means "far enough that Match should say so rather than pretend to know".
--
-- Symmetric, stored once per direction so a lookup is one indexed read rather than an OR
-- over two columns. The seed writes both rows from a single list.
CREATE TABLE public.trade_area_distances (
    from_area_id bigint NOT NULL,
    to_area_id bigint NOT NULL,
    ballast_days numeric(4,1) NOT NULL,

    PRIMARY KEY (from_area_id, to_area_id),
    CONSTRAINT trade_area_distances_from_fkey FOREIGN KEY (from_area_id)
        REFERENCES public.trade_areas(id) ON DELETE CASCADE,
    CONSTRAINT trade_area_distances_to_fkey FOREIGN KEY (to_area_id)
        REFERENCES public.trade_areas(id) ON DELETE CASCADE
);


-- ---------------------------------------------------------------------------
-- 4. Ports get an area
-- ---------------------------------------------------------------------------
-- Optional, and nullable on purpose. 283 ports are on file; this migration fills the ones
-- it can name with confidence and leaves the rest to the people who know them. A port with
-- no area still works everywhere it worked before.
--
-- What it buys: a cargo loading Chornomorsk is a cargo loading in the Black Sea without
-- anybody having said so, so a vessel open "BSEA" is found for it.
ALTER TABLE public.ports
    ADD COLUMN trade_area_id bigint;

ALTER TABLE public.ports
    ADD CONSTRAINT ports_trade_area_id_fkey FOREIGN KEY (trade_area_id)
        REFERENCES public.trade_areas(id) ON DELETE SET NULL;

CREATE INDEX ix_ports_trade_area ON public.ports USING btree (trade_area_id);
